version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      - run: echo "ruby-2.4" > ~/.ruby-version
      - run: sudo gem install bundler
      - run: bundle install
      - run:
          name: die
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test